# Generated by Django 4.2.2 on 2023-06-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('road', '0002_searchform_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
