# Generated by Django 4.2.2 on 2023-06-30 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('road', '0003_remove_utilisateur_login_remove_utilisateur_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivee', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
